# Generated by Django 2.2.6 on 2019-11-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_tercero_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='user',
        ),
    ]
