# Generated by Django 2.2.6 on 2019-11-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_tercero_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N/A', 'No Aplica')], max_length=1),
        ),
    ]
